version: '2'
services:     

    kong-database:
        image: postgres:9.4
        container_name: kong-database
        volumes:
            - "/data/api-gateway/postgres:/var/lib/postgresql/data"
        ports:
            - 5432
        environment:
            - "POSTGRES_USER=kong"
            - "POSTGRES_PASSWORD=kong"
        restart: unless-stopped


    kong-api-gateway:
        image: haufelexware/wicked.kong:latest
        container_name: kong-api-gateway
        depends_on:
            - "kong-database"
        security_opt:
            - seccomp:unconfined
        ports:
            - 8000:8000
            - 8443:8443
            - 8001:8001
        expose:
            - 8000
            - 8443
            - 8001
        environment:
            - "DATABASE=postgres"
            - "VIRTUAL_HOST=https://${PORTAL_NETWORK_APIHOST}:443"
            - "VIRTUAL_HOST_WEIGHT=100"
            - "EXCLUDE_PORTS=7946,8001,8443"
            - "EXTRA_SETTINGS=http-request set-header X-Forwarded-Port %[dst_port]"
            - "SSL_CERT=${GATEWAY_PEM}"
        command: "dockerize -timeout 30s -wait tcp://kong-database:5432 kong start"
        restart: unless-stopped


        
    portal-api:
        env_file: variables.env  
        image: haufelexware/wicked.portal-api:latest
        container_name: portal-api
        volumes:
            - "/data/api-gateway/portal-api-data-static/:/var/portal-api/static/"
            - "/data/api-gateway/portal-api-data-dynamic/:/var/portal-api/dynamic/"
        restart: unless-stopped


    portal:
        env_file: variables.env  
        image: haufelexware/wicked.portal:latest
        container_name: portal
        depends_on:
            - "portal-api"
        ports:
            - 3000:3000
        expose:
            - 3000
        environment:
            - "VIRTUAL_HOST=https://${PORTAL_NETWORK_PORTALHOST}:443"
            - "VIRTUAL_HOST_WEIGHT=0"
            - "SSL_CERT=${PORTAL_PEM}"
        command: "npm start"
        restart: unless-stopped


    portal-kong-adapter:
        env_file: variables.env  
        image: haufelexware/wicked.portal-kong-adapter:latest
        container_name: portal-kong-adapter
        depends_on:
            - "portal-api"
            - "kong-api-gateway"
        restart: unless-stopped
        command: "npm start"






