version: '2'
services:     
    
    kongdb-data:
        image: postgres:9.4
        container_name: kongdb-data
        volumes:
            - "/var/lib/postgresql/data"
        command: "/bin/true"
        
        
    kong-database:
        image: postgres:9.4
        container_name: kong-database
        volumes_from:
            - "kongdb-data"
        ports:
            - 5432
        environment:
            - "POSTGRES_USER=kong"
            - "POSTGRES_PASSWORD=kong"
        restart: unless-stopped


    kong-api-gateway:
        image: haufelexware/wicked.kong:latest
        container_name: kong-api-gateway
        depends_on:
            - "kong-database"
        security_opt:
            - seccomp:unconfined
        ports:
            - 8000:8000
            - 8443:8443
            - 8001:8001
        expose:
            - 8000
            - 8443
            - 8001
        environment:
            - "DATABASE=postgres"
            - "VIRTUAL_HOST=https://${PORTAL_NETWORK_APIHOST}:443"
            - "VIRTUAL_HOST_WEIGHT=100"
            - "EXCLUDE_PORTS=7946,8001,8443"
            - "EXTRA_SETTINGS=http-request set-header X-Forwarded-Port %[dst_port]"
            - "SSL_CERT=${GATEWAY_PEM}"
        command: "dockerize -timeout 30s -wait tcp://kong-database:5432 kong start"
        restart: unless-stopped



    portal-api-data-static:
        build: 
            context: static
        volumes:
            - "/var/portal-api/static"
        command: "/bin/true"        
        
        
    portal-api-data-dynamic:
        image: haufelexware/wicked.portal-api:latest
        volumes:
            - "/var/portal-api/dynamic"
        command: "/bin/true"   
        
        
    portal-api:
        env_file: variables.env  
        image: haufelexware/wicked.portal-api:latest
        volumes_from:
            - "portal-api-data-static"
            - "portal-api-data-dynamic"
        restart: unless-stopped


    portal:
        env_file: variables.env  
        image: haufelexware/wicked.portal:latest
        depends_on:
            - "portal-api"
        expose:
            - "3000"
        environment:
            - "VIRTUAL_HOST=https://${PORTAL_NETWORK_PORTALHOST}:443"
            - "VIRTUAL_HOST_WEIGHT=0"
            - "SSL_CERT=${PORTAL_PEM}"
        command: "npm start"
        restart: unless-stopped









